/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'main': RouteRecordInfo<'main', '/', Record<never, never>, Record<never, never>>,
    '/brief': RouteRecordInfo<'/brief', '/brief', Record<never, never>, Record<never, never>>,
    '/cargo/': RouteRecordInfo<'/cargo/', '/cargo', Record<never, never>, Record<never, never>>,
    '/cargo/item/[clid]/': RouteRecordInfo<'/cargo/item/[clid]/', '/cargo/item/:clid', { clid: ParamValue<true> }, { clid: ParamValue<false> }>,
    '/cargo/item/[clid]/[id]': RouteRecordInfo<'/cargo/item/[clid]/[id]', '/cargo/item/:clid/:id', { clid: ParamValue<true>, id: ParamValue<true> }, { clid: ParamValue<false>, id: ParamValue<false> }>,
    '/load/': RouteRecordInfo<'/load/', '/load', Record<never, never>, Record<never, never>>,
    '/load/area': RouteRecordInfo<'/load/area', '/load/area', Record<never, never>, Record<never, never>>,
    'scene': RouteRecordInfo<'scene', '/scene', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
  }
}
